import Ember from "ember";
import AjaxPromise from 'stock/utils/ajax-promise';
import config from '../../config/environment';

export default Ember.Controller.extend({
  queryParams: ['codeId', 'locationId'],
  codeId: "",
  locationId: "",
  inventoryNumber: "",
  displayInventoryOptions: false,
  autoGenerateInventory: true,
  inputInventory: false,

  isMobileApp: config.cordova.enabled,
  messageBox: Ember.inject.service(),

  code: Ember.computed("codeId", function() {
    return this.get("store").peekRecord("code", this.get("codeId"));
  }),

  location: Ember.computed("codeId", "locationId", function() {
    var locationId = this.get("locationId");
    var location = this.get("store").peekRecord("location", locationId) || this.get("code.location");
    if(!locationId && location) { this.set("locationId", location.get("id")); }
    return location;
  }),

  actions: {
    deleteAutoGeneratedNumber() {
      new AjaxPromise("/inventory_numbers/remove_number", "PUT", this.get('session.authToken'), { code: this.get('inventoryNumber') });
    },

    cancelForm() {
      if(this.get("autoGenerateInventory")) {
        this.send("deleteAutoGeneratedNumber");
      }
      this.set("locationId", "");
      this.set("codeId", "");
      this.transitionToRoute("index");
    },

    toggleInventoryOptions() {
      this.toggleProperty("displayInventoryOptions");
    },

    editInventoryNumber() {
      this.send("deleteAutoGeneratedNumber");
      this.set("inventoryNumber", "");
      this.set("inputInventory", true);
      this.set("autoGenerateInventory", false);
      this.set("displayInventoryOptions", false);
    },

    autoGenerateInventoryNumber() {
      var _this = this;
      this.set("inventoryNumber", "");
      this.set("inputInventory", false);
      this.set("autoGenerateInventory", true);
      this.set("displayInventoryOptions", false);

      new AjaxPromise("/inventory_numbers", "POST", this.get('session.authToken'))
      .then(function(data) {
        _this.set("inventoryNumber", data.inventory_number);
      });
    },

    scanInventoryNumber() {
      this.set("displayInventoryOptions", false);
      this.set("autoGenerateInventory", false);
      this.set("inputInventory", false);
      this.send("deleteAutoGeneratedNumber");

      var _this = this;
      var onSuccess = res => {
        if (!res.cancelled) {
          _this.set("inventoryNumber", res.text);
        }
      };
      var onError = error => this.get("messageBox").alert("Scanning failed: " + error);
      var options = {"formats": "CODE_128"};
      window.cordova.plugins.barcodeScanner.scan(onSuccess, onError, options);
    },

  }

});
