import Ember from "ember";
import AjaxPromise from 'stock/utils/ajax-promise';
import config from '../../config/environment';
const { getOwner } = Ember;

export default Ember.Controller.extend({
  queryParams: ['codeId', 'locationId', 'scanLocationName', 'caseNumber'],
  codeId: "",
  locationId: "",
  inventoryNumber: "",
  scanLocationName: "",
  displayInventoryOptions: false,
  autoGenerateInventory: true,
  inputInventory: false,
  locationName: Ember.computed.alias('location.displayName'),
  caseNumber: "",

  quantity: 1,
  length: null,
  width: null,
  height: null,
  selectedGrade: { name: "B", id: "B" },
  selectedCondition: { name: "Used", id: "U" },
  invalidLocation: false,
  invalidScanResult: false,

  setLocation: Ember.observer("scanLocationName", function() {
    var scanInput = this.get("scanLocationName");
    if(scanInput) {
      var results = this.get("store").peekAll("location").filterBy("displayName", scanInput);
      if(results.length > 0) {
        this.set("invalidScanResult", false);
        this.set("location", results.get("firstObject"));
      } else {
        this.set("invalidScanResult", true);
      }
    } else {
      this.set("invalidScanResult", false);
    }
  }),

  validateLocation: Ember.observer('location', function() {
    if(!this.get("location")) {
      this.set("invalidLocation", false);
    }
  }),

  isMobileApp: config.cordova.enabled,
  messageBox: Ember.inject.service(),

  conditions: Ember.computed(function(){
    return [
      { name: "New", id: "N" },
      { name: "Mixed", id: "M" },
      { name: "Used", id: "U" },
      { name: "Broken", id: "B" }
    ];
  }),

  grades: Ember.computed(function(){
    return [
      { name: "A", id: "A" },
      { name: "B", id: "B" },
      { name: "C", id: "C" },
      { name: "D", id: "D" }
    ];
  }),

  description: Ember.computed("code", {
    get() {
      return this.get("code.name");
    },
    set(key, value) {
      return value;
    }
  }),

  parentCodeName: Ember.computed("codeId", function() {
    var selected = this.get("store").peekRecord("code", this.get("codeId"));
    return selected && selected.get("name");
  }),

  code: Ember.computed("codeId", function() {
    var selected = this.get("store").peekRecord("code", this.get("codeId"));
    return selected && selected.defaultChildPackagesList()[0];
  }),

  location: Ember.computed("codeId", "locationId", {
    get() {
      var locationId = this.get("locationId");
      if(locationId) { this.set("scanLocationName", null); }
      var location = this.get("store").peekRecord("location", locationId) || this.get("code.location");
      if(!locationId && location) { this.set("locationId", location.get("id")); }
      return location;
    },
    set(key, value) {
      return value;
    }
  }),

  actions: {
    clearDescription() {
      this.set("description", "");
    },

    deleteAutoGeneratedNumber() {
      new AjaxPromise("/inventory_numbers/remove_number", "PUT", this.get('session.authToken'), { code: this.get('inventoryNumber') });
    },

    cancelForm() {

      this.get("messageBox").custom(
        "You will lose all your data. Are you sure you want to cancel this item?",
        "Yes",
        () => {
          if(this.get("autoGenerateInventory")) {
            this.send("deleteAutoGeneratedNumber");
          }
          this.set("locationId", "");
          this.set("codeId", "");
          this.transitionToRoute("index");
        },
        "No");
    },

    toggleInventoryOptions() {
      this.toggleProperty("displayInventoryOptions");
    },

    editInventoryNumber() {
      this.send("deleteAutoGeneratedNumber");
      this.set("inventoryNumber", "");
      this.set("inputInventory", true);
      this.set("autoGenerateInventory", false);
      this.set("displayInventoryOptions", false);
    },

    autoGenerateInventoryNumber() {
      var _this = this;
      this.set("inventoryNumber", "");
      this.set("inputInventory", false);
      this.set("autoGenerateInventory", true);
      this.set("displayInventoryOptions", false);

      new AjaxPromise("/inventory_numbers", "POST", this.get('session.authToken'))
      .then(function(data) {
        _this.set("inventoryNumber", data.inventory_number);
      });
    },

    scanInventoryNumber() {
      this.set("displayInventoryOptions", false);
      this.set("autoGenerateInventory", false);
      this.set("inputInventory", false);
      this.send("deleteAutoGeneratedNumber");

      var _this = this;
      var onSuccess = res => {
        if (!res.cancelled) {
          _this.set("inventoryNumber", res.text);
        }
      };
      var onError = error => this.get("messageBox").alert("Scanning failed: " + error);
      var options = {"formats": "CODE_128"};
      window.cordova.plugins.barcodeScanner.scan(onSuccess, onError, options);
    },

    saveItem() {
      var _this = this, loadingView;
      if(
        _this.get("quantity").toString().trim().length === 0 ||
        _this.get("description").trim().length === 0 ||
        !_this.get("location") ||
        _this.get("inventoryNumber").trim().length === 0 ||
        !_this.get('code') ||
        parseInt(_this.get("length")) === 0 ||
        parseInt(_this.get("width")) === 0 ||
        parseInt(_this.get("height")) === 0
      ) {
        if(!_this.get("location")) { this.set("invalidLocation", true); }
        return false;
      } else {

        loadingView = getOwner(this).lookup('component:loading').append();
        var properties = {
          quantity: _this.get("quantity"),
          length: _this.get("length"),
          width: _this.get("width"),
          height: _this.get("height"),
          inventory_number: _this.get("inventoryNumber"),
          case_number: _this.get("caseNumber"),
          notes: _this.get("description"),
          grade: _this.get("selectedGrade.id"),
          donor_condition_id: _this.get("selectedCondition.id"),
          location_id: _this.get("location.id"),
          package_type_id: _this.get("code.id"),
          state_event: 'mark_received'
        };

        new AjaxPromise("/packages", "POST", this.get('session.authToken'), { package: properties })
          .then(data => {
            this.get("store").pushPayload(data);
            loadingView.destroy();
            _this.transitionToRoute("items.detail", data.item.id);
          })
          .catch(response => {
            loadingView.destroy();
            _this.get("messageBox").alert(response.responseJSON.errors[0]);
          });

      }
    }

  }

});
